# Generated by Django 4.0.6 on 2022-07-25 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_remove_quesmodel_category_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quiz.category'),
            preserve_default=False,
        ),
    ]
