# Generated by Django 4.0.6 on 2022-07-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_quesmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='slug',
            new_name='que_slug',
        ),
    ]
