# Generated by Django 4.0.6 on 2022-07-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_rename_slug_question_que_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='question_name',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
